Hw 8
mikhaylovv/otus-go pull request #8
Opened 2020-03-12 12:15 UTC by mikhaylovv

2020-03-16 15:38 UTC, farir1408 requested changes

2020-03-16 15:38 UTC, farir1408 commented on hw_8/calendar/storage/inmemorystorage/in_memory_storage.go
> +	events []storage.Event
Возможно более выгоднее использовать здесь map.

2020-03-16 15:38 UTC, farir1408 commented on hw_8/calendar/storage/storage.go
> +	Date        time.Time
Стоит добавить к Event ID, который генерится стореджем.

2020-03-16 15:38 UTC, farir1408 commented on hw_8/calendar/storage/storage.go
> +	AddEvent(e Event) error
После создания эвента хотелось бы возвращать ID и ошибку.

2020-03-16 15:38 UTC, farir1408 commented on hw_8/calendar/calendar.go
> +	Storage storage.Storage
Это внутрення реализация работы Календаря с хранилищем. Надо бы сделать приватным. А уже у календаря создать публичные мтоды, которые внутри и вызывают методы стореджа.

2020-03-16 17:03 UTC, mikhaylovv commented on hw_8/calendar/storage/storage.go
> +	Date        time.Time
Добавил Id, но не к структуре эвента, а как ключ в мапе

2020-03-16 17:12 UTC, mikhaylovv commented on hw_8/calendar/calendar.go
> +	Storage storage.Storage
пока нет никаких запросов к календарю - не хочу выдумывать несуществующие ручки.  А так да, сделал storage приватным

2020-03-16 17:12 UTC, mikhaylovv commented on hw_8/calendar/storage/storage.go
> +	AddEvent(e Event) error
up

2020-03-16 17:12 UTC, mikhaylovv commented on hw_8/calendar/storage/inmemorystorage/in_memory_storage.go
> +	events []storage.Event
up

2020-03-17 10:57 UTC, farir1408 commented on hw_8/calendar/storage/storage.go
> +	Date        time.Time
Он должен быть и в структуре эвента. Так как ключ в мапе - это своего рода индекс для ускорения поиска.

2020-03-17 10:59 UTC, farir1408 commented on hw_8/calendar/calendar.go
> +	Storage storage.Storage
Эти ручки - это обёртка над методами стореджа. В дз с прикручиванием grpc Вам нужно будет описать эти ручки в прото файле, а потом в имплементации сервиса вызывать ручки календаря. Так что рекомендую описать методы структуры Calendar уже сейчас.

2020-03-31 13:12 UTC, merged