Hw 9
mikhaylovv/otus-go pull request #9
Opened 2020-03-13 09:35 UTC by mikhaylovv

2020-03-23 17:17 UTC, kulti requested changes
Ждем мержа предыдущей части и ребейза этого ПРа.

Функциональность сделана хорошо. Проблемы только в тестах. Предлагаю все-таки использовать стандартный пакет для http сервера и его тестирования.

2020-03-23 17:17 UTC, kulti commented on hw_8/main.go
> +func readConfig(configPath string) ([]byte, error) {
Как я понимаю, смысл этого метода прочитать файл. В ioutil есть готовый метод ReadFile.

2020-03-23 17:17 UTC, kulti commented on hw_8/httpserver/httpserver_test.go
> +	s := &fasthttp.Server{
Предлагаю создавать сервер  в тестах так же, как это делает main. Тогда можно быть уверенным, что протестировано то, что потом будет использоваться.

Чтобы не дублировать создание сервера и скрыть детали реализации предлагаю добавить метод `func httpserver.New(lg Logger) httpserver.HTTPServer`.

Как вариант, можно отказаться от fasthttp и создавать не сервер, а http.Handler. Тогда можно будет использовать в тестах пакет net/http/httptest.

2020-03-23 17:17 UTC, kulti commented on hw_8/httpserver/httpserver_test.go
> +	tearDownHandleTest(t, &f)
В этом случае tearDown сработает только, если в тесте все было хорошо. Неаккуратненько.

2020-03-23 17:17 UTC, kulti commented on hw_8/httpserver/httpserver_test.go
> +		t.Fatalf("unexpected error: %s", err)
Не понимаю, зачем смешивать testify и стандартный пакет для тестов. Тут можно использовать `require.Fail`.

2020-03-23 17:17 UTC, kulti commented on hw_8/httpserver/httpserver_test.go
> +	if err := f.Listener.Close(); err != nil {
Если f.Conn.Close() вернет ошибку, то до сюда код не дойдет. Неаккуратненько.

2020-03-31 13:02 UTC, mikhaylovv commented on hw_8/httpserver/httpserver_test.go
> +	s := &fasthttp.Server{
тут тестируется не совсем структура httpserver, а функция `handle`. Потому что в надо слушать эвенты не на адресе, а на `InmemoryListener'e`. Особенности тестов с fasthttp.
Эту  библиотеку использую, потому что у нас на работе эта же библиотека используется.

2020-04-07 14:03 UTC, merged